// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/rukn-employee/EmployeeView.tsx": () => import("../components/mockups/rukn-employee/EmployeeView.tsx"),
  "./components/mockups/rukn-admin/AdminView.tsx": () => import("../components/mockups/rukn-admin/AdminView.tsx")
};
